TYPO3:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: 'RFY\JWT\Security\Authentication\Provider\PersistedApiTokenProvider'
            token: 'RFY\JWT\Security\Authentication\Token\JwtToken'
            entryPoint: 'HttpBasic'

RFY:
  JsonApi:
    Authenticator:
      signature: 'JSON-API JWT token'