Neos:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: 'RFY\JWT\Security\Authentication\Provider\PersistedApiTokenProvider'
            token: 'RFY\JWT\Security\Authentication\Token\JwtToken'
            entryPoint: 'HttpBasic'

RFY:
  JWT:
    signature: 'JSON-API JWT token'